LOG_LEVEL="DEBUG"
SERVER_ADDRESS="0.0.0.0"
SERVER_PORT=6969
SERVER_TITLE="FAX"
USER_RATE_LIMIT_PER_MINUTES=10
#ESCPOS_USB_IDVENDOR=0x04b8
#ESCPOS_USB_IDPRODUCT=0x0202
#ESCPOS_USB_PROFILE="TM-T88V"
#ESCPOS_USB_LIBUSB1=true
